name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Project 1 tests
        run: dotnet test TestProject1 --no-build --verbosity normal
      - name: Run Project 2 tests
        run: dotnet test TestProject2 --no-build --verbosity normal
      - name: Run Project 3 tests
        run: dotnet test TestProject3 --no-build --verbosity normal
